export const ActionTypes = {
  INCREMENT: '@@honme/INCREMENT', 
  DECREMENT: '@@honme/DECREMENT',
  RESET: '@@home/RESET',


  // COMMON_USER_PRIVILIGE_PENDING: '@@common/COMMON_USER_PRIVILIGE_PENDING', // 获取用户权限信息
  // COMMON_USER_PRIVILIGE_SUCCESS: '@@common/COMMON_USER_PRIVILIGE_SUCCESS',
  // COMMON_USER_PRIVILIGE_FAIL: '@@common/COMMON_USER_PRIVILIGE_FAIL',
}
