export const CommonActions = {
  COMMON_USER_CURRENT: '@@common/COMMON_USER_CURRENT', // 获取用户信息

  COMMON_USER_TOKEN_START: '@@common/COMMON_USER_TOKEN_START',
  COMMON_USER_TOKEN_SUCCESS: '@@common/COMMON_USER_TOKEN_SUCCESS',
  COMMON_USER_TOKEN_FAIL: '@@common/COMMON_USER_TOKEN_FAIL',

  COMMON_USER_PRIVILIGE_PENDING: '@@common/COMMON_USER_PRIVILIGE_PENDING', // 获取用户权限信息
  COMMON_USER_PRIVILIGE_SUCCESS: '@@common/COMMON_USER_PRIVILIGE_SUCCESS',
  COMMON_USER_PRIVILIGE_FAIL: '@@common/COMMON_USER_PRIVILIGE_FAIL',
}
